### PR TITLE
3145535 datetime storage timezone

### PR DESCRIPTION
**Pull request by dww**
See https://www.drupal.org/project/rector/issues/3145535

This now merges cleanly into https://github.com/palantirnet/drupal-rector master.

I addressed the comments at https://github.com/palantirnet/drupal-rector/pull/105 with commit cab2f84524b in this branch.

Thanks and sorry for the noise,
-Derek

### CODE REVIEW

**Comment by dww** [comment]
Sorry, I'm frankly not used to using GH PRs, and my local repo's commits are all fubar as a result. ;)  I don't understand why everyone's so excited about using this workflow.  Seems like much more of a pain in the ass to fork someone else's repo, add multiple upstreams, merge crap all over the place, etc.  Seems like uploading a patch is easier than this. ;)

**Comment by damontgomery** [comment]
Thanks, @dww. I'm going to try and take a look tomorrow.

I'm not sure what caused the recent failures with the automated tests, see https://github.com/palantirnet/drupal-rector/issues/106. I expect yours to fail, but not because of anything you've done. I don't want you to get distracted by that issue.

Thanks again.

**Comment by damontgomery** [comment]
Well. It only took a minute to review the PR and it looks good. Going to try and fix that testing failure tomorrow.

**Comment by dww** [comment]
Sweet, thanks!

**Pull request merged**
