### PR TITLE
Issue #3217942: Bump Rector to 0.11

### PR DESCRIPTION
**Pull request by mglaman**
## Description
Get to the latest Rector minor.

## To Test
Check out this PR and run against a Drupal site, verify 0.11 works as expected.

## Drupal.org issue
https://www.drupal.org/project/rector/issues/3217942

### CODE REVIEW

**Comment by mglaman** [comment]
@agentrickard I re-tried this for kicks, due to PHPUnit being buggy and wondering if we'll have improvements on 0.11.0

The problem.. I can't reproduce or earlier error inside of DDEV :(

**Comment by mglaman** [comment]
Bumping to 0.11.0 _does_ fix the weird PHPUnit autoloading errors: https://github.com/palantirnet/drupal-rector/pull/160

I wonder if the DDEV error is only reproducible when using Docker for Mac? I mean, I wouldn't be surprised :(

**Comment by agentrickard** [comment]
I was planning to test this one and then #160.

I got everything to install correctly after deleting the `vendor` directory and `composer.lock` file, then using this issue as a require statement.

**Comment by agentrickard** [comment]
Runs correctly on Drupal 8, as expected.

**Pull request merged**
