### PR TITLE
Issue #3229883: Scope AssertLegacyTrait rectors based on declaring class

### PR DESCRIPTION
**Pull request by mglaman**
## Description
Target AssertLegacyTrait methods based on declaring sources – no not accidentally clean up AssertContentTrait methods for Kernel tests which pruning deprecated FunctionalTest methods.

## To Test
- Add steps to test this feature

## Drupal.org issue
https://www.drupal.org/project/rector/issues/3229883

### CODE REVIEW

**Comment by agentrickard** [comment]
Not entirely sure what this merge conflict is.

**Comment by mglaman** [comment]
Failures are due to https://github.com/palantirnet/drupal-rector/pull/183

**Comment by agentrickard** [comment]
@mglaman I think this needs to be re-based now that #183 is in?

**Comment by mglaman** [comment]
Well! These are not the failures I expected.

**Comment by mglaman** [comment]
@agentrickard fixed my logic operators, and this looks good to go now

**Pull request merged**
