### PR TITLE
Rector 0.10 with minimal changes.

### PR DESCRIPTION
**Pull request by damontgomery**
This is the work in #134, but without the developer tool changes.

## Remaining work

_If people want to merge this in as a beta release while we work on documentation / support, I'm open to suggestions. See below for a bit more questions around that._

- Review from an end user perspective
- Review of the README from a getting started perspective
- Review of the README from an update perspective
  - This needs to be added, particularly moving from `.yml` to `.php` for the configuration file
- Review of README from a developer perspective
  - I think some of the classes have shifted and we should check if any of the documentation in the README references these old processes. I know we had code examples on various videos / blog posts, but not sure about in the repo.
- Adding comments back to the default configuration file

## Release process request for feedback

Does this make sense as a beta release?

With the changes to the end user and developer experiences, should we coordinate a blog post / video about changes?
- Users are often coming across this tool for the first and only time and supporting resources have been helpful in making that a good experience.

### Requirements
Drupal Rector needs to be installed as a package on a Drupal 8 site. If you would like to use the `drupal-rector-sandbox` project, this may make testing easier since it includes a step to link the examples into the modules folder and creates a `drupal-rector` folder inside the repository where you can use Git to check out branches. If you want to use an existing Drupal 8 project to test this, you will need to update `repositories` in `composer.json` and make sure you download this branch.

### Set up a local testing environment
- Use the `drupal-rector-sandbox` project, https://github.com/palantirnet/drupal-rector-sandbox
- Check out this branch in the `drupal-rector-sandbox/drupal-rector` folder.
  - From within `drupal-rector-sandbox`, `cd drupal-rector`
  - Use this feature branch
    - `git fetch --all`
    - `git checkout origin/rector-0.10-minimal-changes`
- Update composer packages on `drupal-rector-sandbox`
  - `composer update palantirnet/drupal-rector -W`
- Copy the new `.php` configuration file into the sandbox
  - `rm rector.yml` from the `drupal-rector-sandbox` folder
  - `cp drupal-rector/rector.php .` from the `drupal-rector-sandbox` folder

### End user testing notes
- Run `vendor/bin/rector process --dry-run web/modules/custom/rector_examples/db_select.php` or something similar from `drupal-rector-sandbox`.

### Developer testing notes
- Run `composer install` from the `drupal-rector` folder
- Run `vendor/bin/behat` from the `drupal-rector` folder

## Attributions
This is all Matt Glaman's work that was built on the work by Tomas Votruba.

Matt also included a lot of great automated testing / developer tools. Unfortunately, I was not able to get them to work myself, so I wanted to include the work I could verify and keep the (probably temporary) functional Behat tests so that I could test locally / on Github Actions.

If anyone would like to help with the update to the tools that Matt worked on including testing and documentation, it would be greatly appreciated.

### CODE REVIEW

**Comment by goba** [comment]
Not sure of the status of this. I see it was cut back, which I generally agree makes reviewing easier. There was lots of testing of the other PR though at DrupalCon, etc. Do we consider that covered this or does this need more eyes?

**Comment by damontgomery** [comment]
@goba,

I think it would be good to get a few additional people to run the tool locally to see if it works as expected.

It sounds like people were able to provide feedback from the end user perspective.

I'll add a few remaining tasks to the description and I can probably take a look next week.

**Comment by KarinG** [comment]
@goba - asked me to test this. My starting point is my testing of #134 -> 

image

Documenting my testing of this PR #144 

Ok so removing:
```
karins-MBP:palantirnet sysadmin$ rm -rf drupal-rector/
```

Following instructions at the top of this PR:

```
karins-MBP:palantirnet sysadmin$ git clone https://github.com/palantirnet/drupal-rector-sandbox.git
Assuming next step is:
karins-MBP:palantirnet sysadmin$ mv drupal-rector-sandbox drupal-rector
karins-MBP:palantirnet sysadmin$ cd drupal-rector
```

"use this feature branch" -> I only have
```
karins-MBP:drupal-rector sysadmin$ git branch
* master
karins-MBP:drupal-rector sysadmin$ composer install
Creating development environment under drupal-rector/ directory
Clone with SSH
Cloning into 'drupal-rector'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Sorry I can't seem to get this to work!

**Comment by KarinG** [comment]
Ok take two -> this worked to install it:

```
karins-MBP:palantirnet sysadmin$ git clone https://github.com/palantirnet/drupal-rector.git --branch rector-0.10-minimal-changes
karins-MBP:palantirnet sysadmin$ cd drupal-rector
karins-MBP:drupal-rector sysadmin$ composer install

Loading composer repositories with package information
Updating dependencies
Lock file operations: 26 installs, 0 updates, 0 removals
  - Locking behat/behat (v3.8.1)
  - Locking behat/gherkin (v4.8.0)
  - Locking behat/transliterator (v1.3.0)
  - Locking phpstan/phpstan (0.12.85)
  - Locking psr/container (1.1.1)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking rector/rector-prefixed (0.10.21)
  - Locking symfony/config (v5.2.7)
  - Locking symfony/console (v5.2.7)
  - Locking symfony/dependency-injection (v5.2.7)
  - Locking symfony/deprecation-contracts (v2.4.0)
  - Locking symfony/event-dispatcher (v5.2.4)
  - Locking symfony/event-dispatcher-contracts (v2.4.0)
  - Locking symfony/filesystem (v5.2.7)
  - Locking symfony/polyfill-ctype (v1.22.1)
  - Locking symfony/polyfill-intl-grapheme (v1.22.1)
  - Locking symfony/polyfill-intl-normalizer (v1.22.1)
  - Locking symfony/polyfill-mbstring (v1.22.1)
  - Locking symfony/polyfill-php73 (v1.22.1)
  - Locking symfony/polyfill-php80 (v1.22.1)
  - Locking symfony/service-contracts (v2.4.0)
  - Locking symfony/string (v5.2.6)
  - Locking symfony/translation (v5.2.7)
  - Locking symfony/translation-contracts (v2.4.0)
  - Locking symfony/yaml (v5.2.7)
  - Locking webflo/drupal-finder (1.2.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 26 installs, 0 updates, 0 removals
  - Downloading symfony/deprecation-contracts (v2.4.0)
  - Downloading symfony/yaml (v5.2.7)
  - Downloading symfony/translation-contracts (v2.4.0)
  - Downloading symfony/translation (v5.2.7)
  - Downloading psr/event-dispatcher (1.0.0)
  - Downloading symfony/event-dispatcher-contracts (v2.4.0)
  - Downloading symfony/event-dispatcher (v5.2.4)
  - Downloading symfony/service-contracts (v2.4.0)
  - Downloading symfony/dependency-injection (v5.2.7)
  - Downloading symfony/polyfill-intl-grapheme (v1.22.1)
  - Downloading symfony/string (v5.2.6)
  - Downloading symfony/console (v5.2.7)
  - Downloading symfony/filesystem (v5.2.7)
  - Downloading symfony/config (v5.2.7)
  - Downloading behat/transliterator (v1.3.0)
  - Downloading behat/gherkin (v4.8.0)
  - Downloading behat/behat (v3.8.1)
  - Downloading phpstan/phpstan (0.12.85)
  - Downloading rector/rector-prefixed (0.10.21)
  - Installing symfony/polyfill-ctype (v1.22.1): Extracting archive
  - Installing symfony/deprecation-contracts (v2.4.0): Extracting archive
  - Installing symfony/yaml (v5.2.7): Extracting archive
  - Installing symfony/translation-contracts (v2.4.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.22.1): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.22.1): Extracting archive
  - Installing symfony/translation (v5.2.7): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v2.4.0): Extracting archive
  - Installing symfony/event-dispatcher (v5.2.4): Extracting archive
  - Installing psr/container (1.1.1): Extracting archive
  - Installing symfony/service-contracts (v2.4.0): Extracting archive
  - Installing symfony/dependency-injection (v5.2.7): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.22.1): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.22.1): Extracting archive
  - Installing symfony/string (v5.2.6): Extracting archive
  - Installing symfony/polyfill-php73 (v1.22.1): Extracting archive
  - Installing symfony/console (v5.2.7): Extracting archive
  - Installing symfony/filesystem (v5.2.7): Extracting archive
  - Installing symfony/config (v5.2.7): Extracting archive
  - Installing behat/transliterator (v1.3.0): Extracting archive
  - Installing behat/gherkin (v4.8.0): Extracting archive
  - Installing behat/behat (v3.8.1): Extracting archive
  - Installing phpstan/phpstan (0.12.85): Extracting archive
  - Installing rector/rector-prefixed (0.10.21): Extracting archive
  - Installing webflo/drupal-finder (1.2.2): Extracting archive
7 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package rector/rector-prefixed is abandoned, you should avoid using it. Use rector/rector instead.
Generating optimized autoload files
19 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by KarinG** [comment]
"Run vendor/bin/behat" -> I think I'm stuck now:

```
karins-MBP:bin sysadmin$ pwd
/Applications/MAMP/htdocs/d8civicrm.local/vendor/palantirnet/drupal-rector/vendor/bin
karins-MBP:bin sysadmin$ ./behat

In UninitializedContextEnvironment.php line 44:
                                                                 
  `FeatureContext` context class not found and can not be used.  
  
```

**Comment by damontgomery** [comment]
@KarinG,

Thanks for the review!

I'm not sure about your permissions issues, but I'll try to describe what the review could look like. I've also updated the description with better? testing notes.

There are several things I think that need review and the developer experience is one piece and probably not as valuable as the end user perspective, etc. If you want suggestions on where to start with review, I would start with the end user experience / README review.

For either the developer experience or the end user experience, you need a Drupal 8 site and updates to `composer.json` to use this branch instead of the latest stable branch.

This part of the `drupal-rector-sandbox` describes how that was built, https://github.com/palantirnet/drupal-rector-sandbox#how-this-repository-was-built. The key piece here is the folder structure:

/composer.json
/web (docroot)
/vendor (composer packages)
/drupal-rector
/drupal-rector/vendor (development composer packages)

`composer.json` includes this part to load the local version.
```
"repositories": [
        ...
        {
            "type": "path",
            "url": "drupal-rector",
            "options": {
                "symlink": true
            }
        }
    ],
    "require": {
        ...
        "palantirnet/drupal-rector": "dev-master",
    },
```

Thanks again for the review and please let me know if you have any more questions.

**Comment by KarinG** [comment]
@damontgomery - I am a dev and a user: I'm a Drupal module maintainer. 

I successfully used Drupal rector last year to help get our code base from D8->D9 and I was able to easily install @mglaman 's #134 PR during DrupalCon -> and with that PR I was able to successfully run rector on a number of Drupal module projects - including a sizeable one like Webform module and our own Webform CiviCRM module. And yes I did this on a Drupal 8 site (same infra/dev I had previously used Matt's PR on).

I really just tried testing this PR b/c @goba asked me to do so. Sorry I couldn't get it working.

**Comment by damontgomery** [comment]
Thanks again for the feedback, @KarinG.

**Comment by shaal** [comment]
👍 
I tested this PR the same way I tested #134 before, and it ran successfully 💯 

## Testing Instructions
Open a Drupal project (I used DDEV + Gitpod)
https://gitpod.io/#https://github.com/shaal/ddev-gitpod

**Important**: Make sure it's Drupal 8 (and NOT Drupal 9)
```
ddev composer require "drupal/core-recommended:^8.9" "drupal/core-project-message:^8.9" "drupal/core-composer-scaffold:^8.9"
```

Configure it to use latest drupal-rector
```
ddev composer config repositories.1 vcs https://github.com/palantirnet/drupal-rector.git
```

Require the specific branch for this PR
```
ddev composer require palantirnet/drupal-rector:dev-rector-0.10-minimal-changes
```

Configure it
```
cp vendor/palantirnet/drupal-rector/rector.php .
```

Grab the example
```
cp -r vendor/palantirnet/drupal-rector/rector_examples web/modules/
php vendor/bin/rector process web/modules/rector_examples --dry-run
```

Or test with your own modules
```
php vendor/bin/rector process web/modules/custom --dry-run
```

**Comment by damontgomery** [comment]
Thanks for testing @shaal and for the testing notes!

**Review by mglaman — APPROVED** [review]
Cursory overview, it contains the right stuff 👍

**Comment by agentrickard** [comment]
I have created a Drupal.org issue to cover this PR, and recommend that we merge it as a 0.10.x branch, pinned to main here.

https://www.drupal.org/project/rector/issues/3217419

**Pull request merged**
