### PR TITLE
Fix entity_view(), entity_delete_multiple() and EntityTypeInterface::getLowercaseLabel deprecation message

### PR DESCRIPTION
**Pull request by goba**
Neither were added as actually reported by phpstan

## Description

Looked up the actual phpstan messages at https://dev.acquia.com/drupal9/deprecation_status/errors?error=%2AgetLowercaseLabel%2A etc and updating index.

## To Test

N/a

## Drupal.org issue

https://www.drupal.org/project/rector/issues/3224904

### CODE REVIEW

**Comment by goba** [comment]
I do not see why are the particular test is failing, it does not seem to be about the file I am changing?

**Comment by mglaman** [comment]
Tests are failing due to https://github.com/palantirnet/drupal-rector/pull/166

**Comment by agentrickard** [comment]
I have failing tests for a similar PR in #170 even though that branch was opened after #166 went in.

**Comment by mglaman** [comment]
@goba can you rebase this against `main`? I think GitHub has added buttons to do so. But not from the PR screen. Maybe by viewing https://github.com/goba/drupal-rector/tree/patch-7 there is a button?

**Comment by goba** [comment]
Rebased I think, let's see how that works out.

**Review by mglaman — APPROVED** [review]

**Pull request merged**
