### PR TITLE
Support for Drupal 9.

### PR DESCRIPTION
**Pull request by damontgomery**
The packagist automated tests are going to fail because it can't find the files I moved (they aren't there yet.) :)

### CODE REVIEW

**Comment by damontgomery** [comment]
This will probably be tossed after we do the Rector 0.10 update, but I wanted to leave it open as a suggestion on splitting up the rules by major Drupal version.

**Comment by agentrickard** [comment]
I believe we can close this.

**Comment by agentrickard** [comment]
This needs a refactor. See https://www.drupal.org/project/rector/issues/3219156

**Comment by agentrickard** [comment]
This work has been committed elsewhere.

**Pull request closed without merging**
